apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: yynhr-code-pipeline # executable id, must be unique across all your workflows (YAML files), please modify this to any value (e.g. code-pipeline-12345) if you are not the only user of your SAP AI Core instance.
  annotations:
    scenarios.ai.sap.com/description: "yynhr-Tutorial to add custom code to SAP AI Core"
    scenarios.ai.sap.com/name: "yynhr-Code (Tutorial)"
    executables.ai.sap.com/description: "yynhr-Trains model on median house prices"
    executables.ai.sap.com/name: "yynhr-House Price (Sklearn Example)"
  labels:
    scenarios.ai.sap.com/id: "yynhr-learning-code"
    ai.sap.com/version: "2.0"
spec:
  imagePullSecrets:
    - name: yynhr # your docker registry secret
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1

  - name: mycodeblock1
    container:
      image: docker.io/yynhr/house-price:02 # Your docker image name
      command: 
       - python3
      args:
        - "/app/src/main.py"
